{{- if .Values.vernemq.rbac.create -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "vernemq.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "vernemq.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: serviceaccount
    namespace: {{ .Release.Namespace | quote}}
roleRef:
  kind: Role {{/* this must be Role or ClusterRole */}}
  name: {{ include "vernemq.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
