{{- if and .Values.vernemq.rbac.create .Values.vernemq.rbac.serviceAccount.create -}}
{{/* VerneMQ needs to query k8s apiserver to list the other pods in the namespace */}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vernemq.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vernemq.labels" . | nindent 4 }}
{{- end -}}