apiVersion: v1
kind: ConfigMap
metadata:
  name: mqttexplorer-configmap
  namespace: default
data:
  settings.json: |
    {
      "ConnectionManager_connections": {
        "assist-iot": {
          "configVersion": 1,
          "certValidation": false,
          "clientId": "assist-iot-db916df0",
          "id": "assist-iot",
          "name": "assist-iot",
          "encryption": false,
          "subscriptions": [
            {
              "topic": "#",
              "qos": 0
            },
            {
              "topic": "$SYS/#",
              "qos": 0
            }
          ],
          "type": "mqtt",
          "host": "host.docker.internal",
          "protocol": "ws"
        }
      }
    }
